export const PROTOCOL: "afterburner.ui";
export const PROTOCOL_REVISION: 1;
export const COMPATIBILITY_ID: "afterburner.ui.r1";
export const SCHEMA_VERSION: 1;
export const componentKinds: readonly string[];
export const surfaceKinds: readonly string[];
export const envelopeKinds: readonly string[];
export const actionEffects: readonly string[];
export const dataSourceKinds: readonly string[];
export const streamEncodings: readonly string[];
export const streamLifecycles: readonly string[];

export type ComponentNode = {
  id: string;
  kind: string;
  key?: string;
  version?: number;
  props?: Record<string, unknown>;
  children?: ComponentNode[];
  style?: Record<string, unknown>;
  accessibility?: Record<string, unknown>;
  localization?: Record<string, unknown>;
  dataBindings?: string[];
  actionBindings?: Record<string, string>;
  extensionSlots?: unknown[];
  compatibility?: string[];
  metadata?: Record<string, unknown>;
};
export type UIDocument = { root: ComponentNode; revision: number; surfaceId: string; themeId?: string; locale?: string; capabilities?: string[] };
export type PatchOperation = { op: "add" | "remove" | "replace" | "move" | "copy" | "test" | "setProps" | "bindData" | "bindAction"; path: string; from?: string; value?: unknown; guard?: unknown; reason?: string };
export type UIPatch = { schemaVersion?: 1; protocol?: "afterburner.ui"; revision?: 1; surfaceId: string; baseRevision: number; nextRevision: number; operations: PatchOperation[] };
export type SurfaceHandle = { id: string; descriptor: Record<string, unknown>; open(input?: unknown, options?: Record<string, unknown>): Promise<unknown>; update(input?: unknown, options?: Record<string, unknown>): Promise<unknown>; patch(patch: UIPatch, options?: Record<string, unknown>): Promise<unknown>; close(options?: Record<string, unknown>): Promise<unknown>; invoke(actionId: string, parameters?: unknown, options?: Record<string, unknown>): Promise<unknown>; subscribe(listener: (event: unknown) => void, options?: Record<string, unknown>): () => void; fallback(options?: Record<string, unknown>): unknown; diagnostics(): unknown };
export type ExtensionBridge = { ownerExtensionId?: string; runtime: UIRuntime; ui: Record<string, unknown>; registerSurface(descriptor: Record<string, unknown>): unknown; renderSurface(id: string, document: UIDocument | unknown, options?: Record<string, unknown>): Promise<unknown>; patchSurface(id: string, patch: UIPatch, options?: Record<string, unknown>): Promise<unknown>; closeSurface(id: string, options?: Record<string, unknown>): Promise<unknown>; registerObservabilitySink(sink: Record<string, unknown>, listener?: (observation: unknown) => unknown): unknown; subscribeObservability(descriptor: Record<string, unknown>, listener: (observation: unknown) => unknown): unknown; requestCapabilities(declarations: unknown[]): Promise<unknown>; hasCapability(capability: string, resource?: string): boolean; diagnostics(): unknown };

export class UIContractError extends Error { code: string; details: Record<string, unknown>; recoverable: boolean; }
export class UITransportError extends Error { code: string; details: Record<string, unknown>; recoverable: boolean; }
export class MemoryTransport { static pair(): [MemoryTransport, MemoryTransport]; on(event: string, listener: (...args: any[]) => void): this; off(event: string, listener: (...args: any[]) => void): this; write(value: unknown): void; close(): void; }
export class FrameTransport { constructor(stream: unknown, options?: Record<string, unknown>); on(event: string, listener: (...args: any[]) => void): this; off(event: string, listener: (...args: any[]) => void): this; write(value: unknown): void; close(): void; }
export class ProtocolClient { constructor(options?: Record<string, unknown>); connect(options?: Record<string, unknown>): Promise<this>; reconnect(options?: Record<string, unknown>): Promise<this>; close(): void; send(kind: string, payload?: unknown, options?: Record<string, unknown>): Promise<unknown>; snapshot(document: UIDocument, options?: Record<string, unknown>): Promise<unknown>; patch(patch: UIPatch, options?: Record<string, unknown>): Promise<unknown>; event(event: unknown, options?: Record<string, unknown>): Promise<unknown>; lifecycle(payload: unknown, options?: Record<string, unknown>): Promise<unknown>; action(invocation: unknown, options?: Record<string, unknown>): Promise<unknown>; data(sourceId: string, page: unknown, options?: Record<string, unknown>): Promise<unknown>; stream(frame: unknown, options?: Record<string, unknown>): Promise<unknown>; on(event: string, listener: (...args: any[]) => void): this; }
export class UIRuntime { constructor(options?: Record<string, unknown>); defineSurface(definition: Record<string, unknown>): SurfaceHandle; registerSurface(definition: Record<string, unknown>): SurfaceHandle; open(id: string, input?: unknown, options?: Record<string, unknown>): Promise<unknown>; renderSurface(id: string, document: UIDocument | unknown, options?: Record<string, unknown>): Promise<unknown>; update(id: string, next?: unknown, options?: Record<string, unknown>): Promise<unknown>; patch(id: string, patch: UIPatch, options?: Record<string, unknown>): Promise<unknown>; patchSurface(id: string, patch: UIPatch, options?: Record<string, unknown>): Promise<unknown>; close(id: string, options?: Record<string, unknown>): Promise<unknown>; closeSurface(id: string, options?: Record<string, unknown>): Promise<unknown>; invoke(id: string, actionId: string, parameters?: unknown, options?: Record<string, unknown>): Promise<unknown>; subscribe(id: string, listener: (event: unknown) => void, options?: Record<string, unknown>): () => void; fallback(id: string, options?: Record<string, unknown>): unknown; registerObservabilitySink(sink: Record<string, unknown>, listener?: (observation: unknown) => unknown): unknown; subscribeObservability(descriptor: Record<string, unknown>, listener: (observation: unknown) => unknown): unknown; diagnostics(options?: Record<string, unknown>): unknown; }
export class SidecarHost { constructor(options?: Record<string, unknown>); start(): this; stop(reason?: string): void; call(method: string, payload?: unknown, options?: { signal?: AbortSignal }): Promise<unknown>; policyInterface(): unknown; diagnostics(): unknown; on(event: string, listener: (...args: any[]) => void): this; }

export function createNode(kind: string, props?: unknown, children?: unknown, options?: unknown): ComponentNode;
export function createUIDocument(root: ComponentNode, options?: Record<string, unknown>): UIDocument;
export function validateUIDocument(document: UIDocument): UIDocument;
export function validateNode(node: ComponentNode): ComponentNode;
export function validateSurfaceDescriptor(descriptor: Record<string, unknown>): Record<string, unknown>;
export function defineSurface(definition: Record<string, unknown>): SurfaceHandle;
export function registerSurface(definition: Record<string, unknown>): SurfaceHandle;
export function open(id: string, input?: unknown, options?: Record<string, unknown>): Promise<unknown>;
export function renderSurface(id: string, document: UIDocument | unknown, options?: Record<string, unknown>): Promise<unknown>;
export function close(id: string, options?: Record<string, unknown>): Promise<unknown>;
export function closeSurface(id: string, options?: Record<string, unknown>): Promise<unknown>;
export function update(id: string, next?: unknown, options?: Record<string, unknown>): Promise<unknown>;
export function patch(id: string, patch: UIPatch, options?: Record<string, unknown>): Promise<unknown>;
export function patchSurface(id: string, patch: UIPatch, options?: Record<string, unknown>): Promise<unknown>;
export function invoke(id: string, actionId: string, parameters?: unknown, options?: Record<string, unknown>): Promise<unknown>;
export function subscribe(id: string, listener: (event: unknown) => void, options?: Record<string, unknown>): () => void;
export function fallback(id: string, options?: Record<string, unknown>): unknown;
export function registerObservabilitySink(sink: Record<string, unknown>, listener?: (observation: unknown) => unknown): unknown;
export function subscribeObservability(descriptor: Record<string, unknown>, listener: (observation: unknown) => unknown): unknown;
export function diagnostics(): unknown;
export function createRuntime(options?: Record<string, unknown>): UIRuntime;
export function createExtensionBridge(options?: Record<string, unknown>): ExtensionBridge;
export function createProtocolClient(options?: Record<string, unknown>): ProtocolClient;
export function createFrameTransport(stream: unknown, options?: Record<string, unknown>): FrameTransport;
export function createEnvelope(kind: string, payload?: unknown, options?: Record<string, unknown>): Record<string, unknown>;
export function validateEnvelope(envelope: Record<string, unknown>): Record<string, unknown>;
export function createHello(options?: Record<string, unknown>): Record<string, unknown>;
export function negotiateHello(local: Record<string, unknown>, remote: Record<string, unknown>): Record<string, unknown>;
export function encodeFrame(value: unknown, options?: Record<string, unknown>): Buffer;
export function decodeFrame(buffer: Buffer | Uint8Array, options?: Record<string, unknown>): unknown;
export function validatePatch(patch: UIPatch): UIPatch;
export function applyPatch(document: UIDocument, patch: UIPatch): UIDocument;
export function fallbackProjection(document: UIDocument | unknown, options?: Record<string, unknown>): unknown;
export function modalFrameToUIDocument(canvasOrDescriptor: unknown, frame?: unknown, options?: Record<string, unknown>): UIDocument;
export function createModalCanvasCompatibility(legacy?: Record<string, unknown>): { registerModalCanvas(definition: Record<string, unknown>): SurfaceHandle; runtime: UIRuntime };
export function createSidecarHost(options?: Record<string, unknown>): SidecarHost;
export function installSidecarRuntime(handlers?: Record<string, (payload: unknown) => unknown | Promise<unknown>>): () => void;
export function createTestHost(options?: Record<string, unknown>): unknown;
export const components: Record<string, (...args: any[]) => ComponentNode>;
export const application: (...args: any[]) => ComponentNode;
export const window: (...args: any[]) => ComponentNode;
export const surface: (...args: any[]) => ComponentNode;
export const viewport: (...args: any[]) => ComponentNode;
export const stack: (...args: any[]) => ComponentNode;
export const row: (...args: any[]) => ComponentNode;
export const grid: (...args: any[]) => ComponentNode;
export const panel: (...args: any[]) => ComponentNode;
export const card: (...args: any[]) => ComponentNode;
export const separator: (...args: any[]) => ComponentNode;
export const spacer: (...args: any[]) => ComponentNode;
export const text: (...args: any[]) => ComponentNode;
export const markdown: (...args: any[]) => ComponentNode;
export const code: (...args: any[]) => ComponentNode;
export const icon: (...args: any[]) => ComponentNode;
export const badge: (...args: any[]) => ComponentNode;
export const button: (...args: any[]) => ComponentNode;
export const link: (...args: any[]) => ComponentNode;
export const textInput: (...args: any[]) => ComponentNode;
export const textArea: (...args: any[]) => ComponentNode;
export const select: (...args: any[]) => ComponentNode;
export const checkbox: (...args: any[]) => ComponentNode;
export const radioGroup: (...args: any[]) => ComponentNode;
export const toggle: (...args: any[]) => ComponentNode;
export const slider: (...args: any[]) => ComponentNode;
export const progress: (...args: any[]) => ComponentNode;
export const spinner: (...args: any[]) => ComponentNode;
export const list: (...args: any[]) => ComponentNode;
export const table: (...args: any[]) => ComponentNode;
export const tree: (...args: any[]) => ComponentNode;
export const form: (...args: any[]) => ComponentNode;
export const toolbar: (...args: any[]) => ComponentNode;
export const tabs: (...args: any[]) => ComponentNode;
export const breadcrumb: (...args: any[]) => ComponentNode;
export const dialog: (...args: any[]) => ComponentNode;
export const toast: (...args: any[]) => ComponentNode;
export const terminal: (...args: any[]) => ComponentNode;
export const canvas: (...args: any[]) => ComponentNode;
export const image: (...args: any[]) => ComponentNode;
export const video: (...args: any[]) => ComponentNode;
export const chart: (...args: any[]) => ComponentNode;
export const commandPalette: (...args: any[]) => ComponentNode;
export const keybindingHint: (...args: any[]) => ComponentNode;
export const extensionOutlet: (...args: any[]) => ComponentNode;
