package render

import "github.com/nbaertsch/afterburner/internal/ui/component"

const (
	kindRoot          component.Kind = "root"
	kindColumn        component.Kind = "column"
	kindBox           component.Kind = "box"
	kindSection       component.Kind = "section"
	kindSplit         component.Kind = "split"
	kindScroll        component.Kind = "scroll"
	kindDisclosure    component.Kind = "disclosure"
	kindKeyValue      component.Kind = "keyValue"
	kindDetail        component.Kind = "detail"
	kindEmpty         component.Kind = "empty"
	kindTimeline      component.Kind = "timeline"
	kindLog           component.Kind = "log"
	kindMeter         component.Kind = "meter"
	kindBar           component.Kind = "bar"
	kindSparkline     component.Kind = "sparkline"
	kindStatusGrid    component.Kind = "statusGrid"
	kindPasswordInput component.Kind = "passwordInput"
	kindSearchInput   component.Kind = "searchInput"
	kindNumberInput   component.Kind = "numberInput"
	kindDateInput     component.Kind = "dateInput"
	kindFileInput     component.Kind = "fileInput"
	kindActionBar     component.Kind = "actionBar"
	kindContextMenu   component.Kind = "contextMenu"
	kindPagination    component.Kind = "pagination"
	kindHelp          component.Kind = "help"
	kindAlert         component.Kind = "alert"
	kindLoading       component.Kind = "loading"
	kindErrorBoundary component.Kind = "errorBoundary"
	kindConfirmation  component.Kind = "confirmation"
	kindPrompt        component.Kind = "prompt"
)
