package terminal

import "bytes"

const (
	maxTerminalQueryRequestBytes  = 512
	maxTerminalQueryResponseBytes = 512
)

type terminalSequenceStatus int

const (
	terminalSequenceInvalid terminalSequenceStatus = iota
	terminalSequenceIncomplete
	terminalSequenceComplete
)

type terminalSequenceSplitter struct {
	pending    []byte
	maxPending int
	consume    func([]byte) (int, terminalSequenceStatus)
}

func newTerminalQueryRequestSplitter() terminalSequenceSplitter {
	return terminalSequenceSplitter{maxPending: maxTerminalQueryRequestBytes, consume: inspectTerminalQueryRequest}
}

func newTerminalQueryResponseSplitter() terminalSequenceSplitter {
	return terminalSequenceSplitter{maxPending: maxTerminalQueryResponseBytes, consume: inspectTerminalQueryResponse}
}

func (s *terminalSequenceSplitter) Split(data []byte) (matched []byte, remainder []byte) {
	if s.consume == nil {
		remainder = append(remainder, data...)
		return matched, remainder
	}
	if len(s.pending) > 0 {
		combined := make([]byte, 0, len(s.pending)+len(data))
		combined = append(combined, s.pending...)
		combined = append(combined, data...)
		data = combined
		s.pending = nil
	}
	for len(data) > 0 {
		index := bytes.IndexByte(data, 0x1b)
		if index < 0 {
			remainder = append(remainder, data...)
			break
		}
		if index > 0 {
			remainder = append(remainder, data[:index]...)
			data = data[index:]
		}
		consumed, status := s.consume(data)
		switch status {
		case terminalSequenceComplete:
			matched = append(matched, data[:consumed]...)
			data = data[consumed:]
		case terminalSequenceIncomplete:
			if len(data) <= s.maxPending {
				s.pending = append(s.pending[:0], data...)
				return matched, remainder
			}
			remainder = append(remainder, data[0])
			data = data[1:]
		default:
			remainder = append(remainder, data[0])
			data = data[1:]
		}
	}
	return matched, remainder
}

func (s *terminalSequenceSplitter) Reset() {
	s.pending = nil
}

func (s *terminalSequenceSplitter) HasPending() bool {
	return len(s.pending) > 0
}

func (s *terminalSequenceSplitter) PendingLen() int {
	return len(s.pending)
}

func (s *terminalSequenceSplitter) FlushPending() []byte {
	if len(s.pending) == 0 {
		return nil
	}
	pending := append([]byte(nil), s.pending...)
	s.pending = nil
	return pending
}

func (s *terminalSequenceSplitter) PrependPendingAndReset(data []byte) []byte {
	if len(s.pending) == 0 {
		return data
	}
	combined := make([]byte, 0, len(s.pending)+len(data))
	combined = append(combined, s.pending...)
	combined = append(combined, data...)
	s.pending = nil
	return combined
}

// IsTerminalQueryResponse returns true for narrow, well-formed VT replies
// generated by the host terminal in response to Copilot's device/status/cursor
// queries. These bytes must continue to Copilot even while a modal owns human
// presentation; ordinary keystrokes and pasted text are intentionally false.
func IsTerminalQueryResponse(data []byte) bool {
	if len(data) == 0 || len(data) > maxTerminalQueryResponseBytes {
		return false
	}
	for len(data) > 0 {
		consumed, ok := consumeTerminalQueryResponse(data)
		if !ok {
			return false
		}
		data = data[consumed:]
	}
	return true
}

// ExtractTerminalQueryRequests returns the safe terminal query request escape
// sequences embedded in Copilot output. While modal presentation suppresses
// ordinary Copilot rendering, these requests must still reach the host TTY so
// it can generate replies that IsTerminalQueryResponse routes back to Copilot.
func ExtractTerminalQueryRequests(data []byte) []byte {
	out, _ := splitTerminalSequences(data, consumeTerminalQueryRequest)
	return out
}

func SplitTerminalQueryResponses(data []byte) (responses []byte, remainder []byte) {
	return splitTerminalSequences(data, consumeTerminalQueryResponse)
}

func splitTerminalSequences(data []byte, consume func([]byte) (int, bool)) (matched []byte, remainder []byte) {
	for len(data) > 0 {
		index := bytes.IndexByte(data, 0x1b)
		if index < 0 {
			remainder = append(remainder, data...)
			break
		}
		if index > 0 {
			remainder = append(remainder, data[:index]...)
			data = data[index:]
		}
		consumed, ok := consume(data)
		if ok {
			matched = append(matched, data[:consumed]...)
			data = data[consumed:]
			continue
		}
		remainder = append(remainder, data[0])
		data = data[1:]
	}
	return matched, remainder
}

func consumeTerminalQueryRequest(data []byte) (int, bool) {
	consumed, status := inspectTerminalQueryRequest(data)
	return consumed, status == terminalSequenceComplete
}

func inspectTerminalQueryRequest(data []byte) (int, terminalSequenceStatus) {
	if len(data) == 0 || data[0] != 0x1b {
		return 0, terminalSequenceInvalid
	}
	if len(data) < 2 {
		return 0, terminalSequenceIncomplete
	}
	switch data[1] {
	case '[':
		return inspectCSIQueryRequest(data)
	case ']':
		return inspectOSCQueryRequest(data)
	case 'P':
		return inspectDCSQueryRequest(data)
	default:
		return 0, terminalSequenceInvalid
	}
}

func inspectCSIQueryRequest(data []byte) (int, terminalSequenceStatus) {
	for i := 2; i < len(data); i++ {
		if data[i] >= 0x40 && data[i] <= 0x7e {
			body := data[2:i]
			switch data[i] {
			case 'c':
				if validNumericRequestBody(body, true, '?', '>', '=') {
					return i + 1, terminalSequenceComplete
				}
			case 'n':
				if validNumericRequestBody(body, true, '?') {
					return i + 1, terminalSequenceComplete
				}
			case 'p':
				if len(body) > 0 && body[len(body)-1] == '$' && validNumericRequestBody(body[:len(body)-1], true, '?') {
					return i + 1, terminalSequenceComplete
				}
			}
			return 0, terminalSequenceInvalid
		}
		if !isCSIRequestByte(data[i]) {
			return 0, terminalSequenceInvalid
		}
	}
	return 0, terminalSequenceIncomplete
}

func inspectOSCQueryRequest(data []byte) (int, terminalSequenceStatus) {
	bodyEnd, consumed, complete, invalid := scanOSCString(data)
	if invalid {
		return 0, terminalSequenceInvalid
	}
	body := data[2:bodyEnd]
	if len(body) > 256 || !validOSCQueryRequestPrefix(body) {
		return 0, terminalSequenceInvalid
	}
	if !complete {
		return 0, terminalSequenceIncomplete
	}
	if !validOSCQueryRequestBody(body) {
		return 0, terminalSequenceInvalid
	}
	return consumed, terminalSequenceComplete
}

func inspectDCSQueryRequest(data []byte) (int, terminalSequenceStatus) {
	end := bytes.Index(data[2:], []byte{0x1b, '\\'})
	if end < 0 {
		body := data[2:]
		if len(body) > 128 || !validDCSQueryRequestPrefix(body) {
			return 0, terminalSequenceInvalid
		}
		return 0, terminalSequenceIncomplete
	}
	end += 2
	body := data[2:end]
	if len(body) < 2 || len(body) > 128 || !validDCSQueryRequestPrefix(body) {
		return 0, terminalSequenceInvalid
	}
	return end + 2, terminalSequenceComplete
}

func validDCSQueryRequestPrefix(body []byte) bool {
	if len(body) >= 1 && body[0] != '$' {
		return false
	}
	if len(body) >= 2 && body[1] != 'q' {
		return false
	}
	if len(body) <= 2 {
		return true
	}
	for _, b := range body[2:] {
		if b < 0x20 || b > 0x7e {
			return false
		}
	}
	return true
}

func isCSIRequestByte(b byte) bool {
	return (b >= '0' && b <= '9') || b == ';' || b == '?' || b == '>' || b == '=' || b == ':' || b == '$'
}

func validNumericRequestBody(body []byte, allowEmpty bool, prefixes ...byte) bool {
	if len(body) == 0 {
		return allowEmpty
	}
	if containsByte(prefixes, body[0]) {
		body = body[1:]
	}
	if len(body) == 0 {
		return allowEmpty
	}
	return validNumericResponseBody(body, true)
}

func consumeTerminalQueryResponse(data []byte) (int, bool) {
	consumed, status := inspectTerminalQueryResponse(data)
	return consumed, status == terminalSequenceComplete
}

func inspectTerminalQueryResponse(data []byte) (int, terminalSequenceStatus) {
	if len(data) == 0 || data[0] != 0x1b {
		return 0, terminalSequenceInvalid
	}
	if len(data) < 2 {
		return 0, terminalSequenceIncomplete
	}
	switch data[1] {
	case '[':
		return inspectCSIQueryResponse(data)
	case ']':
		return inspectOSCQueryResponse(data)
	case 'P':
		return inspectDCSQueryResponse(data)
	default:
		return 0, terminalSequenceInvalid
	}
}

func inspectCSIQueryResponse(data []byte) (int, terminalSequenceStatus) {
	for i := 2; i < len(data); i++ {
		if data[i] >= 0x40 && data[i] <= 0x7e {
			body := data[2:i]
			if len(body) == 0 {
				return 0, terminalSequenceInvalid
			}
			switch data[i] {
			case 'R':
				if validNumericResponseBody(body, true, '?') {
					return i + 1, terminalSequenceComplete
				}
			case 'c':
				if validNumericResponseBody(body, true, '?', '>') {
					return i + 1, terminalSequenceComplete
				}
			case 'n':
				if validNumericResponseBody(body, true, '?') {
					return i + 1, terminalSequenceComplete
				}
			case 'y':
				if len(body) > 0 && body[len(body)-1] == '$' && validNumericResponseBody(body[:len(body)-1], true, '?') {
					return i + 1, terminalSequenceComplete
				}
			}
			return 0, terminalSequenceInvalid
		}
		if !isCSIResponseByte(data[i]) {
			return 0, terminalSequenceInvalid
		}
	}
	return 0, terminalSequenceIncomplete
}

func inspectOSCQueryResponse(data []byte) (int, terminalSequenceStatus) {
	bodyEnd, consumed, complete, invalid := scanOSCString(data)
	if invalid {
		return 0, terminalSequenceInvalid
	}
	body := data[2:bodyEnd]
	if len(body) > 256 || !validOSCQueryResponsePrefix(body) {
		return 0, terminalSequenceInvalid
	}
	if !complete {
		return 0, terminalSequenceIncomplete
	}
	if !validOSCQueryResponseBody(body) {
		return 0, terminalSequenceInvalid
	}
	return consumed, terminalSequenceComplete
}

func inspectDCSQueryResponse(data []byte) (int, terminalSequenceStatus) {
	end := bytes.Index(data[2:], []byte{0x1b, '\\'})
	if end < 0 {
		body := data[2:]
		if len(body) > 128 || !validDCSQueryResponsePrefix(body) {
			return 0, terminalSequenceInvalid
		}
		return 0, terminalSequenceIncomplete
	}
	end += 2
	body := data[2:end]
	if len(body) < 3 || len(body) > 128 || !validDCSQueryResponsePrefix(body) {
		return 0, terminalSequenceInvalid
	}
	return end + 2, terminalSequenceComplete
}

func validDCSQueryResponsePrefix(body []byte) bool {
	if len(body) >= 1 && (body[0] < '0' || body[0] > '9') {
		return false
	}
	if len(body) >= 2 && body[1] != '$' {
		return false
	}
	if len(body) >= 3 && body[2] != 'r' {
		return false
	}
	if len(body) <= 3 {
		return true
	}
	for _, b := range body[3:] {
		if b < 0x20 || b > 0x7e {
			return false
		}
	}
	return true
}

func isCSIResponseByte(b byte) bool {
	return (b >= '0' && b <= '9') || b == ';' || b == '?' || b == '>' || b == ':' || b == '$'
}

func validNumericResponseBody(body []byte, requireDigit bool, prefixes ...byte) bool {
	if len(body) == 0 {
		return false
	}
	if containsByte(prefixes, body[0]) {
		body = body[1:]
	}
	if len(body) == 0 {
		return false
	}
	sawDigit := false
	lastWasSeparator := true
	for _, b := range body {
		switch {
		case b >= '0' && b <= '9':
			sawDigit = true
			lastWasSeparator = false
		case b == ';' || b == ':':
			if lastWasSeparator {
				return false
			}
			lastWasSeparator = true
		default:
			return false
		}
	}
	if lastWasSeparator {
		return false
	}
	return sawDigit || !requireDigit
}

func scanOSCString(data []byte) (bodyEnd int, consumed int, complete bool, invalid bool) {
	for i := 2; i < len(data); i++ {
		switch data[i] {
		case 0x07:
			return i, i + 1, true, false
		case 0x1b:
			if i+1 >= len(data) {
				return i, 0, false, false
			}
			if data[i+1] == '\\' {
				return i, i + 2, true, false
			}
			return 0, 0, false, true
		default:
			if data[i] < 0x20 || data[i] > 0x7e {
				return 0, 0, false, true
			}
		}
	}
	return len(data), 0, false, false
}

func validOSCQueryRequestPrefix(body []byte) bool {
	return validOSCColorSequence(body, true, false)
}

func validOSCQueryRequestBody(body []byte) bool {
	return validOSCColorSequence(body, true, true)
}

func validOSCQueryResponsePrefix(body []byte) bool {
	return validOSCColorSequence(body, false, false)
}

func validOSCQueryResponseBody(body []byte) bool {
	return validOSCColorSequence(body, false, true)
}

func validOSCColorSequence(body []byte, query bool, complete bool) bool {
	if len(body) == 0 {
		return !complete
	}
	for _, prefix := range [][]byte{[]byte("10;"), []byte("11;"), []byte("12;")} {
		if bytes.HasPrefix(prefix, body) {
			return !complete
		}
		if bytes.HasPrefix(body, prefix) {
			return validOSCPayload(body[len(prefix):], query, complete)
		}
	}
	palettePrefix := []byte("4;")
	if bytes.HasPrefix(palettePrefix, body) {
		return !complete
	}
	if !bytes.HasPrefix(body, palettePrefix) {
		return false
	}
	rest := body[len(palettePrefix):]
	indexEnd := 0
	for indexEnd < len(rest) && rest[indexEnd] >= '0' && rest[indexEnd] <= '9' {
		indexEnd++
	}
	if indexEnd == 0 {
		return false
	}
	if indexEnd == len(rest) {
		return !complete
	}
	if rest[indexEnd] != ';' {
		return false
	}
	return validOSCPayload(rest[indexEnd+1:], query, complete)
}

func validOSCPayload(payload []byte, query bool, complete bool) bool {
	if len(payload) == 0 {
		return !complete
	}
	for _, b := range payload {
		if b < 0x20 || b > 0x7e {
			return false
		}
	}
	if query {
		return len(payload) == 1 && payload[0] == '?'
	}
	return !(len(payload) == 1 && payload[0] == '?')
}

func containsByte(values []byte, target byte) bool {
	for _, value := range values {
		if value == target {
			return true
		}
	}
	return false
}
